name: Eleventy Build Develop
on:
  push:
    branches:
      - develop
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.5.0'
      - name: Install npm packages
        run: npm ci
      - name: Build Deployment Package
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname:
          publish_dir: _site
          publish_branch: gh-pages
          personal_token: ${{ secrets.PERSONAL_TOKEN  }}
